{{- if .Values.externalSecret -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "service.fullname" . }}
spec:
  refreshInterval: "3h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: {{ include "service.fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.externalSecret.secretPath }}
      metadataPolicy: None
{{- end -}}
